# Generated by Django 5.2 on 2025-05-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_pickuppoint_options_pickuppoint_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Резюме')),
                ('status', models.CharField(choices=[('NEW', 'Новая заявка'), ('REVIEW', 'На рассмотрении'), ('INTERVIEW', 'Приглашен на собеседование'), ('REJECTED', 'Отклонено'), ('ACCEPTED', 'Принят')], default='NEW', max_length=20)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pharmacy.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
