# Generated by Django 5.2 on 2025-05-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_vacancyapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='vacancyapplication',
            options={},
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vacancyapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='vacancyapplication',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vacancyapplication',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vacancyapplication',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vacancyapplication',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.customerorder'),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
