# Generated by Django 5.2 on 2025-05-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_pickuppoint_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'verbose_name': 'Пункт выдачи', 'verbose_name_plural': 'Пункты выдачи'},
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
