# Generated by Django 5.2 on 2025-05-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_customuser_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание обязанностей'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='info@pharmacy.by', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Сотрудник', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='Общий', max_length=100, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='+375 (29) 123-45-67', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Специалист', max_length=100, verbose_name='Должность'),
        ),
    ]
