# Generated by Django 5.2 on 2025-05-27 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отклик на вакансию', 'verbose_name_plural': 'Отклики на вакансии'},
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pharmacy.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='cover_letter',
            field=models.TextField(blank=True, verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/', verbose_name='Резюме'),
        ),
        migrations.AddConstraint(
            model_name='vacancyapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False), ('vacancy__isnull', False)), fields=('user', 'vacancy'), name='unique_user_vacancy_application'),
        ),
    ]
